### ISSUE TITLE
Add general descriptor information to echemdb data apckages.

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/metadata-schema#17]
The echemdb datapackages should contain the following descriptors.
* [Link to datapackage schema](https://specs.frictionlessdata.io/schemas/data-package.json)
* [Link to a description of the schema](https://specs.frictionlessdata.io/data-package/#language)

I try to keep the following part up to date based on further discussions.
```yaml
name: url of the echemdb datapackage schema
id: ?
title: echemdb datapackage
description: a short description of the datapackage
profile: usually a tabular-data-package, which we do not have. Instead use maybe descriptive-tabular-data-package
homepage: git repo
created: ?
contributors: The echemdb authors
keywords: ?
image: ?
licence: same as echemdb
sources: ?
resources:
  - name: filepath
    path: filepath
    title: raw data
  - name: echemdb
    data: inline data inferred from filename
  - name: integrated charge # optional, results from data processing
    path: path
  - name: filepath_c1 # optional, results from data processing
    path: filepath_c1
```
