### ISSUE TITLE
Add key atmosphere to electrolyte

### ISSUE THREAD

**Issue by mkheubach** [echemdb/metadata-schema#23]
describes atmosphere above the electrolyte
```yaml=
    atmosphere:
        type: xxx # UHV/laboratory/glovebox/inert chamber
        components:
        - name: Ar
          source: 
            supplier: MTI
            supplied purity:
              grade: N5.0
          type: gas
          pressure:
            unit: 1
            value: bar # use 1 bar for saturated solutions
          proportion:
            value: 100
          flow:
            value: null
            unit: null
```
