### ISSUE TITLE
Field description of echemdb datapackages

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/metadata-schema#26]
Some thoughts on creating a metadata standard for the field description in the echemdb datapackage.

From frictionless [fields schema](https://specs.frictionlessdata.io/table-schema/#field-descriptors)
```python
{
  "name": "name of field (e.g. column name)",
  "title": "A nicer human readable label or title for the field",
  "type": "A string specifying the type",
  "format": "A string specifying a format",
  "example": "An example value for the field",
  "description": "A description for the field",
  "constraints": {
      // a constraints-descriptor
  }
}
```

echemdb should have something like this:

```python
{
  "name": "name of field (e.g. column name)",
  "title": "A nicer human readable label or title for the field",
  "dimension": "The dimension of the field",
  "unit": "The unit of the field",
  "description": "A description for the field",
  "reference": "Applicable to fields with a potential",
}
```
currently, it looks somewhat like this:

`names = ['t', 'E', 'I', 'j'] `

Since they should be unique 'E' is not so smart since 
it can be E of the working electrode or E of a secondary electrode. 
(the same thing applies to j and I)
't' could also be the absolute time or the relative time.

I suggest the following change suggestion:

```yaml
names = ['t_rel', 't_abs', 'E_WE', 'E_CE', 'E_collector', 'j_WE', 'j_CE']
# the titles could be composed of 'dimension' and 'unit'. 
# Here we do not distinguish between working and counter elecrode
title = ['t [s]', 'E [V vs Ref]', 'E [V]']
# the description could contain more information on the field
description_E_WE = 'Working electrode potential'
description_j_collector = 'current density at the ring electrode'

# what we need for echemdb (including things that might come and are already relevant in the lab)
names = ['t_rel', 't_abs', 
         'E_WE', 'E_CE', 'E_collector', 
         'j_WE', 'j_CE', 'j_collector',
         'I_WE', 'I_CE', 'I_collector']

```

Finally an example:

```yaml
fields:
 - name: t_rel
   original name: time (s) 
   title: t / s
   dimension: t
   unit: s
   description: The relative time with respect to the first data point in this series.
 - name: E_WE2
   original name: WE(2).potential (V)
   title: E / V vs RHE
   dimension: E
   unit: V
   description: Potential at the secondary collector electrode.
   reference: RHE
   
```
