### ISSUE TITLE
suggested metadata structure for sample preparation

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/metadata-schema#29]
suggested metadata structure
```yaml
preparation:
    type: UHV #ambient conditions, UHV, etc
    steps:
    - Sputtering with Argon.
    - Annealing at 1500 K
    - Cooling in an O2 atmosphere
```

_Originally posted by @DunklesArchipel in https://github.com/echemdb/website/issues/156#issuecomment-1163185670_
