### ISSUE TITLE
Add institution to persons in the curation schema

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/metadata-schema#64]
Currently we only require the name and ORCID for each person in the curation process, but it might be helpful to include the current institution.

```yaml
process:
  - role: curator # the first role is usually the experimentalist
    name: Albert Engstfeld
    orcid: https://orcid.org/0000-0002-9686-3948
    date: 2021-07-09 # YYYY-MM-DD
    institution: Institute of nice experiment
  - role: reviewer
    name: Albert Engstfeld
    orcid: https://orcid.org/0000-0002-9686-3948
    date: 2022-01-21
```
